import { duplicateMediaName, normalizeMediaName } from '../media-names.mjs';
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

import LocationMap from './LocationMap';
import CoordinatePicker from './CoordinatePicker';
import LoginPage from './LoginPage';
import LocationSearch from './LocationSearch';
import PageNavigation from './PageNavigation';
import { ProblemList, ProblemForm, ProblemPage, AttachMediaForm, problemHref } from './Problems';

const uid = () => crypto.randomUUID();
const countLabel = (count, noun) => `${count} ${noun}${count === 1 ? '' : 's'}`;
const symbols = { pin: '◎', mountain: '△', plus: '+', arrow: '↗', photo: '▧' };
function Icon({ name }) { return <span aria-hidden="true" className="icon">{symbols[name]}</span>; }
async function api(path, options) {
  const response = await fetch(path, options);
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Something went wrong. Please try again.');
  return data;
}
function Modal({ title, children, close }) {
  const ref = useRef();
  useEffect(() => { ref.current.showModal(); }, []);
  return <dialog ref={ref} onCancel={e => e.preventDefault()}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close" onClick={close}>×</button></div>{children}</dialog>;
}
function App() {
  const videoMaxMB = 100;
  const [user, setUser] = useState(null), [loginPage, setLoginPage] = useState((!location.hash || location.hash === '#' || location.hash === '#login'));
  const canEdit = item => !!user && (user.role === 'admin' || item?.createdBy === user.id);
  useEffect(() => { const refresh = () => api('/api/session').then(data => setUser(data.user)).catch(() => setUser(null)); refresh(); window.addEventListener('focus', refresh); return () => window.removeEventListener('focus', refresh); }, []);
  const [db, setDb] = useState({ revision: 0, locations: [] }), [loaded, setLoaded] = useState(false);
  const [locationId, setLocationId] = useState(null), [boulderId, setBoulderId] = useState(null);
  const [problemId, setProblemId] = useState(null);
  const [modal, setModal] = useState(null), [error, setError] = useState('');
  const [busy, setBusy] = useState(false), [toast, setToast] = useState('');
  useEffect(() => { api('/api/guide').then(data => { setDb(data); setLocationId(new URLSearchParams(location.hash.slice(1)).get('location')); setBoulderId(new URLSearchParams(location.hash.slice(1)).get('boulder')); setProblemId(new URLSearchParams(location.hash.slice(1)).get('problem')); setLoaded(true); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 3500); return () => clearTimeout(t); } }, [toast]);
  useEffect(() => {
    const navigate = () => { setLoginPage((!location.hash || location.hash === '#' || location.hash === '#login')); const params = new URLSearchParams(location.hash.slice(1)); setLocationId(params.get('location')); setBoulderId(params.get('boulder')); setProblemId(params.get('problem')); setModal(null); window.scrollTo(0, 0); };
    window.addEventListener('hashchange', navigate);
    return () => window.removeEventListener('hashchange', navigate);
  }, []);
  const place = db.locations.find(l => l.id === locationId);
  const boulder = place?.boulders.find(b => b.id === boulderId);
  const problem = boulder?.problems?.find(p => p.id === problemId);
  const choose = (l, b = null, p = null) => { setLocationId(l); setBoulderId(b); setProblemId(p); location.hash = new URLSearchParams({ location: l, ...(b ? { boulder: b } : {}), ...(p ? { problem: p } : {}) }); };
  async function logout() { try { await api('/api/logout', { method: 'POST' }); setUser(null); setModal(null); location.hash = '#login'; } catch (e) { setError(e.message); } }
  async function save(next) {
    setBusy(true); setError('');
    try { const result = await api('/api/guide', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); setDb(result); setToast('Changes saved'); return true; }
    catch (e) { setError(e.message); return false; } finally { setBusy(false); }
  }
  const updatePlace = async patch => save({ ...db, locations: db.locations.map(l => l.id === place.id ? { ...l, ...patch } : l) });
  const updateBoulder = async patch => {
    const next = { ...boulder, ...patch };
    next.problems = (next.problems || []).map(p => ({ ...p, imageIds: p.imageIds.filter(id => next.images.some(i => i.id === id)), videoIds: p.videoIds.filter(id => (next.videos || []).some(v => v.id === id)) }));
    return updatePlace({ boulders: place.boulders.map(b => b.id === boulder.id ? next : b) });
  };
  async function submit(e) {
    e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget));
    for (const field of ['approach', 'notes']) if (field in form) { form[field] = form[field].trim(); if (!form[field]) { setError(field === 'approach' ? 'Approach notes are required.' : 'Finding the Boulder is required.'); return; } }
    form.name = form.name.trim(); if (!form.name) { setError('Please enter a name.'); return; }
    if (modal === 'location' || modal === 'editLocation') {
      const latitude = form.latitude.trim(), longitude = form.longitude.trim();
      if (!latitude || !longitude) { setError('Enter both latitude and longitude.'); return; }
      const item = { id: uid(), region: '', boulders: [], ...form, latitude, longitude };
      const ok = modal === 'location' ? await save({ ...db, locations: [...db.locations, item] }) : await updatePlace(form);
      if (ok) { setModal(null); if (modal === 'location') choose(item.id); }
    } else {
      const item = { id: uid(), images: [], videos: [], problems: [], ...form };
      const ok = modal === 'boulder' ? await updatePlace({ boulders: [...place.boulders, item] }) : await updateBoulder(form);
      if (ok) { setModal(null); if (modal === 'boulder') choose(place.id, item.id); }
    }
  }
  function prepareUpload(e, kind) {
    const files = [...e.target.files]; e.target.value = ''; if (!files.length) return;
    const existing = kind === 'photo' ? (boulder ? boulder.images : place.photos || []) : boulder.videos || [];
    const prefix = kind === 'photo' ? 'Photo' : 'Video';
    const used = new Set(existing.map(item => normalizeMediaName(item.name)));
    let number = existing.length + 1;
    const names = files.map(() => { while (used.has(normalizeMediaName(prefix + ' ' + number))) number++; const name = prefix + ' ' + number++; used.add(normalizeMediaName(name)); return name; });
    setError(''); setModal({ nameUploads: { files, names, kind } });
  }
  const upload = e => prepareUpload(e, 'photo');
  const uploadVideos = e => prepareUpload(e, 'video');
  async function uploadNamedPhotos(files, names, captions = []) {
    setBusy(true); setError('');
    try {
      const images = [];
      for (const file of files) {
        if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) throw new Error('Choose JPEG, PNG, or WebP images.');
        if (file.size > 8 * 1024 * 1024) throw new Error('Each image must be smaller than 8 MB.');
        const result = await api('/api/images', { method: 'POST', headers: { 'Content-Type': file.type }, body: file });
        images.push({ id: uid(), name: names[images.length], caption: captions[images.length] || '', url: result.url, annotations: [] });
      }
      const saved = !boulder ? await updatePlace({ photos: [...(place.photos || []), ...images] }) : await updateBoulder({ images: [...boulder.images, ...images], ...(problem ? { problems: boulder.problems.map(p => p.id === problem.id ? { ...p, imageIds: [...p.imageIds, ...images.map(image => image.id)] } : p) } : {}) });
      if (saved) setModal(null);
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function uploadNamedVideos(files, names) {
    setBusy(true); setError('');
    try {
      for (const file of files) {
        if (!['video/mp4', 'video/webm', 'video/quicktime'].includes(file.type) && !/\.mov$/i.test(file.name)) throw new Error('Choose MP4, WebM, or MOV videos.');
        if (file.size > videoMaxMB * 1024 * 1024) throw new Error(`Each video must be smaller than ${videoMaxMB} MB.`);
      }
      const videos = [];
      for (const file of files) {
        const result = await api('/api/videos', { method: 'POST', headers: { 'Content-Type': /\.mov$/i.test(file.name) ? 'video/quicktime' : file.type }, body: file });
        videos.push({ id: uid(), name: names[videos.length], url: result.url });
      }
      const saved = await updateBoulder({ videos: [...(boulder.videos || []), ...videos], ...(problem ? { problems: boulder.problems.map(p => p.id === problem.id ? { ...p, videoIds: [...p.videoIds, ...videos.map(video => video.id)] } : p) } : {}) });
      if (saved) setModal(null);
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  const home = !locationId;
  const goHome = () => { setLocationId(null); setBoulderId(null); setProblemId(null); location.hash = '#explore'; };
  return <div className="app">
    <div className="workspace"><header className="topbar"><a className="brand" href={user ? "#explore" : "#login"} aria-label="SideProj home"><span className="brand-mark" aria-hidden="true">△</span> Side<span className="brand-light">Proj</span></a><div className="header-actions">{user ? <><span className="signed-in">{user.name} <small>{user.role}</small></span><button className="secondary small" onClick={logout}>Log out</button></> : !loginPage && <a className="secondary small" href="#login">Log in</a>}</div></header>
    {loginPage ? <LoginPage onLogin={async identity => { setUser(identity); setDb(await api('/api/guide')); location.hash = '#explore'; }}/>: <main className={home ? "search-home" : "location-page"}>
    {error && !modal?.nameUploads && <div role="alert" className="error">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}
    {home ? <><LocationSearch locations={db.locations} loaded={loaded} canCreate={!!user} busy={busy} onCreate={() => { setError(''); setModal('location'); }}/><LocationMap locations={db.locations} selectedId={null} onSelect={id => choose(id)}/></> : <>
    <section id="location-details" className="detail-panel">{!place ? <div className="welcome"><PageNavigation place={place} boulder={boulder} problem={problem} problemId={problemId}/><h2>{loaded ? 'Location not found' : 'Loading location...'}</h2>{loaded && <p>This location may have been removed. Return to search to find another location.</p>}</div> : <>
    {!boulder && <div className="detail-banner"><PageNavigation place={place} boulder={boulder} problem={problem} problemId={problemId}/><div className="eyebrow"><Icon name="pin"/> {place.region || 'CLIMBING LOCATION'}</div><h2>{place.name}</h2><p className="created-by">Created by {place.createdByName || place.createdBy || 'Climber'}</p><div className="banner-bottom"><span>{countLabel(place.boulders.length, 'boulder')} · {countLabel(place.boulders.reduce((s, b) => s + (b.problems || []).length, 0), 'problem')} · {countLabel(place.boulders.reduce((s, b) => s + b.images.length, 0), 'photo')} · {countLabel(place.boulders.reduce((s, b) => s + (b.videos || []).length, 0), 'video')}</span><div className="location-actions"><button disabled={busy || !canEdit(place)} onClick={() => { setError(''); setModal('editLocation'); }}>Edit location ↗</button><button disabled={busy || !canEdit(place)} onClick={() => { setError(''); setModal({ removeLocation: place }); }}>Remove location</button></div></div></div>}
    {boulder && !problemId && <div className="detail-banner boulder-banner"><PageNavigation place={place} boulder={boulder} problem={problem} problemId={problemId}/><div className="eyebrow">BOULDER</div><h1>{boulder.name}</h1><p className="created-by">Created by {boulder.createdByName || boulder.createdBy || 'Climber'}</p><div className="banner-bottom"><span>{countLabel((boulder.problems || []).length, 'problem')} · {countLabel(boulder.images.length, 'photo')} · {countLabel((boulder.videos || []).length, 'video')}</span><div className="location-actions"><button disabled={busy || !canEdit(boulder)} onClick={() => { setError(''); setModal('editBoulder'); }}>Edit boulder</button>{canEdit(boulder) && <button disabled={busy} onClick={() => { setError(''); setModal({ removeBoulder: boulder }); }}>Remove boulder</button>}</div></div></div>}
    {problemId && boulder ? <ProblemPage removePhoto={image => { setError(''); setModal({ unlinkPhoto: image }); }} attach={kind => { setError(''); setModal({ attachMedia: kind }); }} upload={upload} uploadVideos={uploadVideos} canEdit={canEdit(problem)} navigation={<PageNavigation place={place} boulder={boulder} problem={problem} problemId={problemId}/>} problem={problem} boulder={boulder} busy={busy} remove={() => { setError(''); setModal({ removeProblem: problem }); }} edit={() => { setError(''); setModal({ problemForm: true, problem }); }} annotate={image => { setError(''); setModal({ image: { ...image, annotations: problem.photoAnnotations?.[image.id] || [] }, problemId: problem.id }); }} Shapes={Shapes}/> : boulder ? <><div className="notes-block"><h3>Finding the Boulder</h3><p className="preserve">{boulder.notes || 'Describe how to find this boulder after following the location approach notes. Include nearby landmarks, paths, and distances.'}</p></div>{boulder.otherNotes && <div className="notes-block"><h3>Other Notes</h3><p className="preserve">{boulder.otherNotes}</p></div>}<ProblemList place={place} boulder={boulder} busy={busy || !user} add={() => { setError(''); setModal({ problemForm: true }); }}/><div className="section-heading photos-heading"><div><h3>Photos</h3><p>Photos of the boulder. Photos uploaded here can be annotated on problem pages to highlight the line and its holds.</p></div><label className={`secondary small upload ${busy || !user ? 'disabled' : ''}`}>+ Upload images<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy || !user} onChange={upload}/></label></div>{!boulder.images.length ? <div className="photo-empty"><Icon name="photo"/><h3>Upload an image here.</h3><p>Upload a boulder photo, then link and annotate it from a problem page.</p><span>JPEG, PNG, WebP · up to 8 MB each</span></div> : <div className="photo-grid">{boulder.images.map(img => <div className="photo-item" key={img.id}><div className="photo-card"><div className="photo-thumb"><img src={img.url} alt={img.name}/></div><div><span>{img.name}</span></div></div><button className="remove-media" disabled={busy || !canEdit(img)} aria-label={`Remove image ${img.name}`} onClick={() => { setError(''); setModal({ remove: img, collection: 'images' }); }}>Remove image</button></div>)}</div>}
    <section aria-labelledby="beta-videos-heading"><div className="section-heading photos-heading"><div><h3 id="beta-videos-heading">Beta videos</h3><p>Steal beta to become a better climber.</p></div><label className={`secondary small upload ${busy || !user ? 'disabled' : ''}`}>{busy ? 'Please wait...' : '+ Upload video'}<input type="file" accept="video/mp4,video/webm,video/quicktime,.mov" multiple disabled={busy || !user} onChange={uploadVideos}/></label></div>

    {!(boulder.videos || []).length ? <div className="photo-empty"><h3>Spray beta here.</h3><p>Upload a video showing your beta for a problem at this boulder.</p><span>MP4, WebM, or MOV · up to {videoMaxMB} MB each</span></div> : <div className="video-grid">{boulder.videos.map(video => <figure className="video-card" key={video.id}><video controls playsInline preload="metadata" src={video.url} aria-label={video.name}>Your browser does not support this video.</video><figcaption>{video.name}<div className="video-actions"><a href={`${video.url}?download=${encodeURIComponent(video.name)}`} download={video.name}>Download</a><button className="remove-media" disabled={busy || !canEdit(video)} aria-label={`Remove video ${video.name}`} onClick={() => { setError(''); setModal({ remove: video, collection: 'videos' }); }}>Remove video</button></div></figcaption><p>If playback is unavailable, download the original video.</p></figure>)}</div>}</section>
    </> : <><div className="location-info"><div><h3><Icon name="pin"/> Coordinates</h3>{place.latitude && place.longitude ? <><p className="coordinates">{Number(place.latitude).toFixed(5)}, {Number(place.longitude).toFixed(5)}</p><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${place.latitude},${place.longitude}`)}`}>Open in maps ↗</a></> : <button className="text-button" disabled={!canEdit(place)} onClick={() => setModal('editLocation')}>+ Add coordinates</button>}</div><div><h3>Approach notes</h3><p className="preserve">{place.approach || 'Add parking details, the path to follow, and access information.'}</p></div></div><section><div className="section-heading photos-heading"><div><h3>Parking & Approach Photos</h3><p>Photos to help find the parking and approach.</p></div><label className={`secondary small upload ${busy || !user ? 'disabled' : ''}`}>+ Upload photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy || !user} onChange={upload}/></label></div>{place.photos?.length ? <div className="photo-grid">{place.photos.map(photo => <figure className="problem-photo" key={photo.id}><div className="photo-thumb"><img src={photo.url} alt={photo.caption || photo.name}/></div><figcaption><strong>{photo.name}</strong><p className="preserve">{photo.caption}</p>{canEdit(photo) && <div className="problem-media-actions"><button className="secondary small" disabled={busy} onClick={() => { setError(''); setModal({ locationCaption: photo }); }}>Edit caption</button><button className="remove-media" disabled={busy} onClick={() => { setError(''); setModal({ removeLocationPhoto: photo }); }}>Remove photo</button></div>}</figcaption></figure>)}</div> : <p className="problem-empty">No parking or approach photos yet.</p>}</section><div className="section-heading boulders-heading"><div><h3>Boulders <span className="count">{place.boulders.length}</span></h3><p>The boulders at {place.name}.</p></div><button className="secondary small" disabled={busy || !user} onClick={() => setModal('boulder')}>+ Add boulder</button></div>{!place.boulders.length ? <div className="photo-empty"><Icon name="mountain"/><h3>A location full of possibilities.</h3><p>Add the first boulder to start adding problems, photos and videos.</p></div> : <div className="boulder-list">{place.boulders.map((b, i) => <button className="boulder-row" key={b.id} onClick={() => choose(place.id, b.id)}><span className="boulder-avatar">{b.images[0] ? <img src={b.images[0].url} alt=""/> : <Icon name="mountain"/>}</span><div><span className="eyebrow">BOULDER {String(i + 1).padStart(2, '0')}</span><strong>{b.name}</strong><p>{b.notes || 'Add directions to this boulder'}</p></div><span className="boulder-meta">{countLabel((b.problems || []).length, 'problem')} · {countLabel(b.images.length, 'photo')} · {countLabel((b.videos || []).length, 'video')}</span><span>↗</span></button>)}</div>}</>}
    </>}</section></>}<footer>SideProj <span>A better way to share our love for climbing.</span></footer></main>}</div>
    {modal?.locationCaption && <Modal title="Edit caption" close={() => { if (!busy) { setError(''); setModal(null); } }}><form onSubmit={async e => { e.preventDefault(); const caption = new FormData(e.currentTarget).get('caption').trim(); if (await updatePlace({ photos: place.photos.map(p => p.id === modal.locationCaption.id ? { ...p, caption } : p) })) setModal(null); }}><label>Caption (optional)<textarea name="caption" rows="4" maxLength={2000} defaultValue={modal.locationCaption.caption || ''}/></label>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy}>Save caption</button></div></form></Modal>}
    {modal?.removeLocationPhoto && <Modal title="Remove location photo?" close={() => { if (!busy) { setError(''); setModal(null); } }}><p>Remove {modal.removeLocationPhoto.name} from this location?</p>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => { setError(''); setModal(null); }}>Cancel</button><button className="danger-button" disabled={busy} onClick={async () => { if (await updatePlace({ photos: place.photos.filter(p => p.id !== modal.removeLocationPhoto.id) })) setModal(null); }}>Remove photo</button></div></Modal>}
    {modal?.nameUploads && <Modal title={modal.nameUploads.kind === 'photo' ? 'Name your photo' : 'Name your video'} close={() => { if (!busy) { setError(''); setModal(null); } }}><form onSubmit={e => { e.preventDefault(); const names = new FormData(e.currentTarget).getAll('mediaName').map(name => name.trim()); if (names.some(name => !name)) { setError('Enter a name for each file.'); return; } const { files, kind } = modal.nameUploads; const duplicate = duplicateMediaName(kind === 'photo' ? boulder.images : boulder.videos || [], names); if (duplicate !== null) { setError(`A ${kind} named "${duplicate}" already exists for this boulder. Choose a different name.`); return; } (kind === 'photo' ? uploadNamedPhotos : uploadNamedVideos)(files, names, new FormData(e.currentTarget).getAll('caption').map(value => value.trim())); }}>{modal.nameUploads.files.map((file, index) => <label key={index}><input aria-label={`${modal.nameUploads.kind === 'photo' ? 'Photo' : 'Video'} ${index + 1} name`} autoFocus={index === 0} name="mediaName" required maxLength={255} disabled={busy} defaultValue={modal.nameUploads.names[index]}/>{!boulder && <><span>Caption (optional)</span><textarea name="caption" rows="3" maxLength={2000} disabled={busy} placeholder="Describe the parking spot, path, or landmark shown."/></>}</label>)}{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={() => { setError(''); setModal(null); }}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Uploading...' : 'Upload'}</button></div></form></Modal>}
    {modal?.unlinkPhoto && <Modal title="Remove photo from problem?" close={() => { if (!busy) setModal(null); }}><p>Remove <strong>{modal.unlinkPhoto.name}</strong> from this problem? The original photo will remain on the boulder and any other problems using it.</p>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Cancel</button><button className="danger-button" disabled={busy || !canEdit(problem)} onClick={async () => { const id = modal.unlinkPhoto.id; if (await updateBoulder({ problems: boulder.problems.map(p => p.id === problem.id ? { ...p, imageIds: p.imageIds.filter(imageId => imageId !== id) } : p) })) { setModal(null); setToast('Photo removed from problem'); } }}>{busy ? 'Removing...' : 'Remove photo'}</button></div></Modal>}
    {modal?.removeBoulder && <Modal title="Remove boulder?" close={() => { if (!busy) setModal(null); }}><p className="preserve">Remove <strong>{modal.removeBoulder.name}</strong> and all its problems, photos, annotations, and beta videos from the guide? This cannot be undone.</p>{user?.role !== 'admin' && <p>You can only remove this boulder if all its submissions are yours.</p>}{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Cancel</button><button className="danger-button" disabled={busy || !canEdit(modal.removeBoulder)} onClick={async () => { const id = modal.removeBoulder.id; if (await updatePlace({ boulders: place.boulders.filter(b => b.id !== id) })) { setModal(null); choose(place.id); setToast('Boulder removed'); } }}>{busy ? 'Removing...' : 'Remove boulder'}</button></div></Modal>}
    {modal?.removeProblem && <Modal title="Remove problem?" close={() => { if (!busy) setModal(null); }}><p className="preserve">Remove <strong>{modal.removeProblem.name}</strong> from this boulder? This cannot be undone. Its linked photos and videos will remain on the boulder.</p>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async () => { const id = modal.removeProblem.id; if (await updateBoulder({ problems: (boulder.problems || []).filter(p => p.id !== id) })) { setModal(null); choose(place.id, boulder.id); setToast('Problem removed'); } }}>{busy ? 'Removing...' : 'Remove problem'}</button></div></Modal>}
    {modal?.attachMedia && <Modal title={`Add ${modal.attachMedia} from ${boulder.name} page`} close={() => { if (!busy) setModal(null); }}><AttachMediaForm locationId={place.id} boulder={boulder} problem={problem} kind={modal.attachMedia} busy={busy} error={error} cancel={() => setModal(null)} save={async (field, ids) => { if (await updateBoulder({ problems: boulder.problems.map(p => p.id === problem.id ? { ...p, [field]: [...new Set([...p[field], ...ids])] } : p) })) setModal(null); }}/></Modal>}
    {modal?.problemForm && <Modal title={modal.problem ? 'Edit problem' : 'Add problem'} close={() => { if (!busy) setModal(null); }}><ProblemForm boulder={boulder} problem={modal.problem} busy={busy} error={error} cancel={() => setModal(null)} save={async item => { const problems = modal.problem ? boulder.problems.map(p => p.id === item.id ? { ...p, ...item } : p) : [...(boulder.problems || []), item]; if (await updateBoulder({ problems })) { setModal(null); choose(place.id, boulder.id, item.id); } }}/></Modal>}
    {typeof modal === 'string' && <Modal title={modal === 'location' ? 'Create a location' : modal === 'editLocation' ? 'Edit location' : modal === 'boulder' ? 'Add a boulder' : 'Edit boulder'} close={() => setModal(null)}><form onSubmit={submit}>{error && <p className="error" role="alert">{error}</p>}{modal.toLowerCase().includes('location') ? <><label>Location name <span aria-hidden="true">*</span><input autoFocus name="name" required maxLength={120} defaultValue={modal === 'editLocation' ? place.name : ''} placeholder="Fontainebleau"/></label><CoordinatePicker initialLatitude={modal === 'editLocation' ? place.latitude : ''} initialLongitude={modal === 'editLocation' ? place.longitude : ''}/><label>Approach notes <span aria-hidden="true">*</span><textarea required name="approach" rows="5" maxLength={10000} defaultValue={modal === 'editLocation' ? place.approach : ''} placeholder="Where to park, how to get there, and what to know about access. You can include links to Google Maps Street View images to help show the parking or approach."/></label></> : <><label>Boulder name <span aria-hidden="true">*</span><input autoFocus name="name" required maxLength={120} defaultValue={modal === 'editBoulder' ? boulder.name : ''} placeholder="e.g. The Pebble"/></label><label>Finding the Boulder <span aria-hidden="true">*</span><textarea required name="notes" rows="7" maxLength={10000} defaultValue={modal === 'editBoulder' ? boulder.notes : ''} placeholder="From the end of the location approach, describe the path, landmarks, and distances to this boulder…"/></label><label>Other Notes<textarea name="otherNotes" rows="4" maxLength={10000} defaultValue={modal === 'editBoulder' ? boulder.otherNotes || '' : ''} placeholder="Describe the rock type, recommended mat placement, whether access or climbing depends on the tide, and any other useful details."/></label></>}<div className="form-actions"><button type="button" className="secondary" onClick={() => setModal(null)}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save '+ (modal.toLowerCase().includes('location') ? 'location' : 'boulder')}</button></div></form></Modal>}
    {modal?.removeLocation && <Modal title="Remove location?" close={() => { if (!busy) setModal(null); }}><p className="preserve">Remove <strong>{modal.removeLocation.name}</strong> from your guide? All of its boulders, notes, photos, annotations, and beta videos will also be removed from the guide. This cannot be undone.</p>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async () => { const id = modal.removeLocation.id; if (await save({ ...db, locations: db.locations.filter(location => location.id !== id) })) { setModal(null); goHome(); setToast('Location removed'); } }}>{busy ? 'Removing...' : 'Remove location'}</button></div></Modal>}
    {modal?.remove && <Modal title={modal.collection === 'images' ? 'Remove image?' : 'Remove video?'} close={() => { if (!busy) setModal(null); }}><p className="preserve">Remove <strong>{modal.remove.name}</strong> from this boulder?{modal.collection === 'images' ? ' Its annotations will also be removed.' : ''}</p>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async () => { const { collection, remove } = modal; if (await updateBoulder({ [collection]: (boulder[collection] || []).filter(item => item.id !== remove.id) })) { setModal(null); setToast(collection === 'images' ? 'Image removed' : 'Video removed'); } }}>{busy ? 'Removing...' : 'Remove'}</button></div></Modal>}
    {modal?.image && <AnnotationEditor error={error} image={modal.image} close={() => setModal(null)} busy={busy} save={async annotations => { if (await updateBoulder({ problems: boulder.problems.map(p => p.id === modal.problemId ? { ...p, photoAnnotations: { ...p.photoAnnotations, [modal.image.id]: annotations } } : p) })) setModal(null); }}/>}<div className="toast" role="status">{toast}</div>
  </div>;
}
function Shapes({ items, draft, ...props }) {
  return <svg viewBox="0 0 1000 1000" preserveAspectRatio="none" {...props}><g opacity="0.5">{[...items, ...(draft ? [draft] : [])].map((s, i) => {
    const stroke = s.color === 'green' ? '#35df79' : '#ff2929';
    if (s.type === 'box') return <rect key={i} stroke={stroke} x={Math.min(s.x, s.x2)} y={Math.min(s.y, s.y2)} width={Math.abs(s.x2 - s.x)} height={Math.abs(s.y2 - s.y)} />;
    if (s.type === 'arrow') {
      const angle = Math.atan2(s.y2 - s.y, s.x2 - s.x), size = Math.min(30, Math.hypot(s.x2-s.x, s.y2-s.y) / 2);
      return <g key={i} stroke={stroke}><line x1={s.x} y1={s.y} x2={s.x2} y2={s.y2}/><polyline points={[[s.x2-size*Math.cos(angle-.5),s.y2-size*Math.sin(angle-.5)],[s.x2,s.y2],[s.x2-size*Math.cos(angle+.5),s.y2-size*Math.sin(angle+.5)]].map(p=>p.join(',')).join(' ')}/></g>;
    }
    return s.type === 'line' ? <line key={i} stroke={stroke} x1={s.x} y1={s.y} x2={s.x2} y2={s.y2}/> : <polyline key={i} stroke={stroke} points={s.points.map(p => p.join(',')).join(' ')}/>;
  })}</g></svg>;
}
function AnnotationEditor({ image, close, save, busy, error }) {
  const [items, setItems] = useState(image.annotations), [draft, setDraft] = useState(null), [tool, setTool] = useState('start');
  const drawing = useRef(null);
  const point = e => { const r = e.currentTarget.getBoundingClientRect(); return [Math.max(0, Math.min(1000, (e.clientX - r.left) / r.width * 1000)), Math.max(0, Math.min(1000, (e.clientY - r.top) / r.height * 1000))]; };
  function start(e) { if (e.button !== 0) return; e.currentTarget.setPointerCapture(e.pointerId); const [x, y] = point(e); drawing.current = { type: tool === 'start' ? 'box' : tool, color: tool === 'start' ? 'green' : 'red', x, y, x2: x, y2: y, points: [[x, y]] }; setDraft(drawing.current); }
  function move(e) { if (!drawing.current) return; const [x2, y2] = point(e); drawing.current = { ...drawing.current, x2, y2, points: [...drawing.current.points, [x2, y2]] }; setDraft(drawing.current); }
  function finish(e) { if (!drawing.current) return; move(e); const s = drawing.current; if (Math.abs(s.x2 - s.x) + Math.abs(s.y2 - s.y) > 2 || s.points.length > 3) setItems(old => [...old, s]); drawing.current = null; setDraft(null); }
  return <Modal title="Annotate photo" close={close}>{error && <p className="error" role="alert">{error}</p>}<div className="annotation-toolbar" role="group" aria-label="Drawing tools">{[['start', '□ Start holds · green'], ['box', '□ Other holds · red'], ['arrow', '↗ Arrow'], ['line', '╱ Line'], ['freehand', '〰 Freehand']].map(([key, label]) => <button key={key} className={'tool annotation-tool annotation-tool-' + key + (tool === key ? ' active' : '')} aria-pressed={tool === key} onClick={() => setTool(key)}>{label}</button>)}<button className="tool" disabled={!items.length} onClick={() => setItems(items.slice(0, -1))}>↶ Undo</button><button className="tool" disabled={!items.length} onClick={() => setItems([])}>Clear</button></div><p className="annotation-help">Mark the holds or line for this problem</p><div className="annotation-stage"><img src={image.url} alt={image.name} draggable="false"/><Shapes items={items} draft={draft} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={() => { drawing.current = null; setDraft(null); }} aria-label="Photo annotation canvas"/></div><div className="form-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy} onClick={() => save(items)}>{busy ? 'Saving…' : 'Save annotations'}</button></div></Modal>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);

